#!/bin/sh
# HISTFILE="$XDG_DATA_HOME"/zsh/history
HISTSIZE=1000000
SAVEHIST=1000000
export PATH="$HOME/.local/bin":$PATH
export MANPAGER='nvim +Man!'
export MANWIDTH=999
export VISUAL='nvim'
export EDITOR=${VISUAL}
export GIT_EDITOR=${VISUAL}
#export PATH=$HOME/.fnm:$PATH
#eval "$(fnm env)"
#eval "$(zoxide init zsh)"
#eval "`pip completion --zsh`"

# GH
export BROWSER="open -a Google\ Chrome.app"

# Add ASDF plugin
[ -f $HOME/.asdf/asdf.sh ] && source $HOME/.asdf/asdf.sh
# completions for asdf to fpath
fpath=(${ASDF_DIR}/completions $fpath)
# initialise completions with ZSH's compinit
[[ -n ${ZDOTDIR}/.zcompdump(#qN.mh+24) ]] && compinit || compinit -C

# NVM
export NVM_DIR="$HOME/.nvm"
[ -s "/usr/local/opt/nvm/nvm.sh" ] && \. "/usr/local/opt/nvm/nvm.sh"  # This loads nvm
[ -s "/usr/local/opt/nvm/etc/bash_completion.d/nvm" ] && \. "/usr/local/opt/nvm/etc/bash_completion.d/nvm"  # This loads nvm bash_completion

# Global config for permissions on NodeJS (https://stackoverflow.com/a/55274930/234110)
export PATH=~/.npm-global/bin:$PATH

# Go
export PATH=$HOME/.local/share/go/bin:$PATH
#export GOPATH=$HOME/.local/share/go

# Python
# for PYTHON_BIN in $(ls -d -1 /usr/local/opt/python@3*/bin); do export PATH=$PYTHON_BIN:$PATH; done
# for PYTHON_LIB in $(ls -d -1 /usr/local/opt/python@3*/lib); do export LDFLAGS="-L${PYTHON_LIB} $LDFLAGS"; done
# for PKG_CONFIG_PATH in $(ls -d -1 /usr/local/opt/python@3*/lib/pkgconfig); do export PKG_CONFIG_PATH=$PYTHON_PKG:$PKG_CONFIG_PATH; done
PYTHON_PATH=/usr/local/opt/python@3
export PATH=$PYTHON_PATH/bin:$PATH

# PY_ENV
export PYENV_ROOT="$HOME/.pyenv"
command -v pyenv >/dev/null || export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init -)"

# Ruby
export PATH="/usr/local/opt/ruby/bin:$PATH"
export LDFLAGS="-L/usr/local/opt/ruby/lib $LDFLAGS"
export CPPFLAGS="-I/usr/local/opt/ruby/include $CPPFLAGS"

# Rust
append_path $HOME/.cargo/bin

export PATH
