#!/bin/sh

append_path () {
  case ":$PATH:" in
    *:"$1":*)
    ;;
  *)
    if [ -d "$1" ]; then
      PATH="${PATH:+$PATH:}$1"
    fi
  esac
}

append_path "$HOME/.local/bin"
# append_path $HOME/.fnm
# eval "$(fnm env)"
# eval "$(zoxide init zsh)"
# eval "`pip completion --zsh`"

# GH
export BROWSER="open -a Google\ Chrome.app"

# NVM
export NVM_DIR="$HOME/.nvm"
[ -s "/usr/local/opt/nvm/nvm.sh" ] && \. "/usr/local/opt/nvm/nvm.sh"  # This loads nvm
[ -s "/usr/local/opt/nvm/etc/bash_completion.d/nvm" ] && \. "/usr/local/opt/nvm/etc/bash_completion.d/nvm"  # This loads nvm bash_completion

# Global config for permissions on NodeJS (https://stackoverflow.com/a/55274930/234110)
append_path ~/.npm-global/bin

# Golang
# append_path "$(go env GOPATH)/bin"
# append_path $HOME/.local/share/go/bin
# append_path $HOME/.local/share/go

# PYENV
# command -v pyenv >/dev/null || append_path "$PYENV_ROOT/bin" && eval "$(pyenv init -)"
# export PYENV_ROOT=$HOME/.config/pyenv/

# Python
# for PYTHON_BIN in $(ls -d -1 /usr/local/opt/python@3*/bin); do export PATH=$PYTHON_BIN:$PATH; done
# for PYTHON_LIB in $(ls -d -1 /usr/local/opt/python@3*/lib); do export LDFLAGS="-L${PYTHON_LIB} $LDFLAGS"; done
# for PKG_CONFIG_PATH in $(ls -d -1 /usr/local/opt/python@3*/lib/pkgconfig); do export PKG_CONFIG_PATH=$PYTHON_PKG:$PKG_CONFIG_PATH; done

# PYTHON_PATH=/usr/local/opt/python@3
# append_path $PYTHON_PATH/bin
# export LDFLAGS="-L${PYTHON_PATH}/lib $LDFLAGS"
# export PKG_CONFIG_PATH=$PYTHON_PATH/lib/pkgconfig:$PKG_CONFIG_PATH

# Ruby
# append_path "/usr/local/opt/ruby/bin"
# append_path ~/.local/share/gem/ruby/3.0.0/bin
# export LDFLAGS="-L/usr/local/opt/ruby/lib $LDFLAGS"
# export CPPFLAGS="-I/usr/local/opt/ruby/include $CPPFLAGS"

# Rust
append_path $HOME/.cargo/bin

# FZF - May mess with nvim's telescope
# export FZF_DEFAULT_COMMAND='rg --hidden -l ""'

# Add RVM to PATH for scripting. Make sure this is the last PATH variable change.
append_path $HOME/.rvm/bin

# ASDF
# completions for asdf to fpath
fpath=(${ASDF_DIR}/completions $fpath)
append_path $HOME/.asdf/shims

# Remove duplicate entries from PATH:
# PATH=$(echo "$PATH" | awk -v RS=':' -v ORS=":" '!a[$1]++{if (NR > 1) printf ORS; printf $a[$1]}')

export PATH
